### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by SanjaySRocks** [Cruze03/discord-utilities#29]
L 12/09/2021 - 01:14:59: [discord_api.smx] [DISCORD] Couldn't Retrieve Messages - Fail 0 400

flooding server with this error, verification works fine.
what can be an issue and how to fix it?

**Comment by Cruze03** [comment]
Is it fixed now @SanjaySRocks ?

**Comment by SanjaySRocks** [comment]
Yes, solved don't know exactly how it got fixed.
