### ISSUE TITLE
Bug with CallAdminReportTitle in discord

### ISSUE THREAD

**Issue by MickaNoob** [Cruze03/discord-utilities#36]
Hi, I have detected a bug with the DU --> Calladmin .

The message for new calladmins is not displayed correctly, the title (CallAdminReportTitle) is missing. 

CallAdminReportTitle is present in tranlastion, but not working 

```
	"CallAdminReportTitle"
	{
		"en"		"New Calladmin"
		"fr"		"Nouveau CallAdmin"
		"hu"		"Egy jelentést éppen kezelnek!"
		"nl"		"De CallAdmin Report wordt behandelt!"
		"lv"		"CallAdmin Ziņojums tiek izskatīts!"
		"ru"		"CallAdmin Репорт обрабатывается!"
		"ro"		"CallAdmin Report se gestionează!"
	}
```

![bug1](https://user-images.githubusercontent.com/20491694/178126687-229bf6f4-9932-4cd8-81da-f1fc6d3c01d2.png)

Check Images.

**Comment by MickaNoob** [comment]
Hi, 

I have found  same bug with the "bug report". 

Default:
```
	char buffer[512], trans[64];
	Format( trans, sizeof( trans ), "%T", "BugReportTitle", LANG_SERVER);
	embed.SetTitle( buffer );
```
Fixed version : 
```
	char buffer[512], trans[64];
	Format( trans, sizeof( trans ), "%T", "BugReportTitle", LANG_SERVER);
	embed.SetTitle( trans );
```
![image](https://user-images.githubusercontent.com/20491694/180441287-48d494a6-234a-45d8-a624-df35151ce365.png)

![image](https://user-images.githubusercontent.com/20491694/180441331-40217516-cf28-4c99-a50e-6a7dee5ef873.png)

**Comment by Cruze03** [comment]
Wow, reasonable because they both are almost copy-pasta! Thanks for notifying though!
