### ISSUE TITLE
Discord Server > Game Server relay not functioning as intended.

### ISSUE THREAD

**Issue by MerryMonkedas** [Cruze03/discord-utilities#38]
I am having an issue with the Discord Server > Game Server relay not functioning properly. For the past 2-3 months it has worked fine but just recently instead of posting the discord users message through to the game server, it does the [Discord] tag, their username, and then where the message is meant to be is blank. I have reinstalled Discord Utilites, done fresh wipes of the Discord-Utilities.cfg file, deleted the database file, and yet nothing seems to work. Any assistance would be amazing, and thank you for your time. 
![image](https://user-images.githubusercontent.com/108565271/189514340-8995c46f-9398-446f-8bfa-df3ffb72224b.png)

**Comment by Cruze03** [comment]
[Added a new section in troubleshoot](https://github.com/Cruze03/discord-utilities/wiki/Troubleshoot#discord-to-gameserver-is-sending-blank-message--verification-bot-is-not-responding-as-it-should)

**Comment by MerryMonkedas** [comment]
I appreciate the assistance, was stuck on it for ages!
