### ISSUE TITLE
memory leak/ failed to send webhook 0 0

### ISSUE THREAD

**Issue by xSL0W** [Cruze03/discord-utilities#6]
Hello, i fixed this problem:
discord_utilities/forwards.sp

```
public Action OnLogAction(Handle hSource, Identity ident, int client, int target, const char[] sMsg)
{
	if(StrEqual(g_sAdminLog_Webhook, ""))
	{
		return Plugin_Continue;
	}
	
	if(client <= 0)
	{
		return Plugin_Continue;
	}

	if(StrContains(sMsg, "sm_chat", false) != -1)
	{
		return Plugin_Continue;// dont log sm_chat because it's already being showed in admin chat relay channel.
	}
	
	SendAdminLog(client, sMsg);

	return Plugin_Continue;
}
```

managed to fix it by adding 
```
if(StrEqual(g_sAdminLog_Webhook, ""))
	{
		return Plugin_Continue;
	}
```

I didnt used this module, so my URL was blank. This was causing an exception somewhere deeper in the code and throwed error Failed to send webhook 0 0 everytime LogMessage occured from a plugin. This caused a memleak too.

**Comment by xSL0W** [comment]
btw and also always check a webhook key to be valid, != "" before sending a chat relay or something like this

**Comment by Cruze03** [comment]
Thanks <3 Added this in latest version: https://discordapp.com/channels/734350057431629925/735398210541060128/754065594868826323
